name: build-and-push

on:
  push:
    branches: [release]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push image
        run: |
          TAG="release-$(git rev-parse --short HEAD)"
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker build -t "docker.io/foreverlovewisdom/gitops-app-demo:${TAG}" .
          docker push "docker.io/foreverlovewisdom/gitops-app-demo:${TAG}"
